basePath: /api/v1
definitions:
  auth.LoginForm:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.RegisterForm:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  follow.FollowRequest:
    properties:
      follower_id:
        type: integer
      leader_id:
        type: integer
    required:
    - follower_id
    - leader_id
    type: object
  models.User:
    properties:
      created_at:
        type: string
      id:
        type: integer
      last_login:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  termsOfService: http://swagger.io/terms/
  title: GoUGC
  version: "1.0"
paths:
  /auth/login/:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Login User
      tags:
      - Auth
  /auth/register/:
    post:
      consumes:
      - application/json
      description: Register User
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Register User
      tags:
      - Auth
  /follow/:
    delete:
      consumes:
      - application/json
      description: UnFollow User
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/follow.FollowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: UnFollow User
      tags:
      - Follow
    post:
      consumes:
      - application/json
      description: Follow User
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/follow.FollowRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Follow User
      tags:
      - Follow
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
